# Use official OpenJDK image
FROM openjdk:21-slim

# Set work directory
WORKDIR /app

# Add built jar file (this will be generated by Maven/Gradle)
COPY target/inventory-service-0.0.1-SNAPSHOT.jar app.jar


# Expose port (change if needed)
EXPOSE 8080

# Run the app
ENTRYPOINT ["java", "-jar", "app.jar"]
